# Generated by Django 4.2.30 on 2026-06-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='queue_type',
            field=models.CharField(choices=[('physical', 'Physical'), ('virtual', 'Virtual')], default='physical', max_length=10),
        ),
    ]
