# Generated by Django 4.2.30 on 2026-06-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
