# Generated by Django 4.2.30 on 2026-06-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(choices=[('registrar', 'Registrar'), ('finance', 'Finance'), ('health', 'Health Clinic'), ('library', 'Library'), ('ict', 'ICT Support'), ('student_affairs', 'Student Affairs'), ('admissions', 'Admissions'), ('cafeteria', 'Cafeteria')], default='registrar', max_length=30)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_time', models.TimeField(default='08:00')),
                ('closing_time', models.TimeField(default='17:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
